### ISSUE TITLE
Smartphone Search

### ISSUE THREAD

**Issue by rjahn** [LeonStaufer/material-dokuwiki#10]
Search field is too wide on mobile devices - Portrait mode. Works in landscape mode.

**Comment by LeonStaufer** [comment]
Thanks for the feedback.

What do you mean by too wide? What would be your preferred width?

For me it looks like this on mobile devices:
![screenshot of search bar on mobile](https://s9.postimg.org/vrx9kpktb/searchonmobile.png) 


I purposely designed it, so that when you click the search icon, it expands to fill 80% of the screen.

**Comment by rjahn** [comment]
It looks like this one:

<img width="375" alt="material_sh" src="https://user-images.githubusercontent.com/1307043/35512957-b8f4ed38-0501-11e8-86fb-541558497a94.png">

**Comment by LeonStaufer** [comment]
Huh, that is definitely a bug and shouldn't happen. Thanks for letting me know.

Does the issue occur on all mobile devices or just some? Could you please let me know which device it is, so I examine what might be causing this issue?

**Comment by rjahn** [comment]
We fixed this problem in our system: https://doc.sibvisions.com

All "tested" devices (Android, iOS) - not all available devices :)

**Comment by LeonStaufer** [comment]
Ah okay, so you hide the logo. I suppose that works too. 
When researching what the problem might be, I have discovered that it doesn't work in [a couple browsers](https://caniuse.com/#feat=css-focus-within).

I will look for a better way of expanding the search bar in the future.
