### ISSUE TITLE
doesn't work with draw.io plugin

### ISSUE THREAD

**Issue by thomaspz** [LeonStaufer/material-dokuwiki#35]
The material-theme is very cool and a straight forward layout. I used it for a while.
Now, I installed the draw.io plugin, but it doesn't open the draw.io editor. When I change to another theme, the draw.io plugin works as expected.

**Comment by LeonStaufer** [comment]
This is because the iframe created by the draw.io plugin does not specify a z-index. This results in it being below the layout elements of Material Design Lite. I have created a [new issue](https://github.com/lejmr/dokuwiki-plugin-drawio/issues/20) in the plugin repository. 

In the meantime, you can fix the issue by adding the following custom CSS to your DokuWiki installation:
```css
iframe.drawio {
    z-index: 999;
}
```
